# Site settings
title: This Is the Bru
email: #
description: > # this means to ignore newlines until "baseurl:"
  Some ramblings, experiments, and other stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thisisthebru.com/" # the base hostname & protocol for your site
twitter_username: thebru1905
github_username:  theBru
linkedin_username: gurur

# Build settings
markdown: kramdown
