# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: This Is the Bru
email: #
description: > # this means to ignore newlines until "baseurl:"
  Some ramblings, experiments, and other stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thisisthebru.com/" # the base hostname & protocol for your site
twitter_username: thebru1905
github_username:  theBru
linkedin_username: gurur

# Build settings
markdown: kramdown
